spring:
  profiles:
    active: development
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/masterarbeit?currentSchema=Masterarbeit
    username: postgres
    password:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate: 
      ddl-auto: update
logging: 
  level: 
    ROOT: INFO
server:
  error:
    include-stacktrace: never
  port: 9300
  servlet:
    context-path: /secure-hsm-service
