spring:
  profiles:
    active: development
management:
  server:
    port: 9401
  endpoints:
    enable-by-default: true
    web:
      exposure:
        include: health, info
server:
  error:
    include-stacktrace: never
  port: 9400
  servlet:
    context-path: /secure-hsm-data
logging: 
  level: 
    ROOT: INFO
remote-crypto-data:
  authentication: abc
  storage: ./target/data-storage